In [13]:
from sklearn.metrics import classification_report
import torch
import pandas as pd
from tqdm import tqdm
import transformers
from transformers import AutoModelForMaskedLM, AutoModelForSequenceClassification,AutoTokenizer, AutoModel, AutoConfig, utils
from transformers import pipeline

RuntimeError: module compiled against API version 0x10 but this version of numpy is 0xf

RuntimeError: Failed to import transformers.pipelines because of the following error (look up to see its traceback):
initialization of _pywrap_checkpoint_reader raised unreported exception

In [ ]:
pip install transformers

In [3]:
#!pip install transformers
#!pip show transformers
#!pip install torch torchvision
#!pip install -U scikit-learn
#!pip install openpyxl

In [4]:
orig_sentence_file =  "../Project2_Gaze4Hate/gaze4hate_sentences_to_annotate.xlsx"
orig_df = pd.read_excel(open(orig_sentence_file, 'rb'), sheet_name='stimuli') 

## remove the 4 familiarization sentences (last four)
orig_df= orig_df.loc[orig_df['Cond_remark']!='fam']

In [5]:
orig_df.Cond_remark.unique()

array(['hate_w_high', 'no_hate_w', 'hate_w_med', 'hate_m', 'neutral_w',
       'pos_w'], dtype=object)

In [6]:
orig_df

Sno  Condition  Cond_remark  ID  \
0     1          1  hate_w_high  27   
1     2          1  hate_w_high  26   
2     3          1  hate_w_high  16   
3     4          1  hate_w_high  14   
4     5          1  hate_w_high   2   
..  ...        ...          ...  ..   
85   89          3        pos_w  28   
86   90          3        pos_w  32   
87   91          3        pos_w   1   
88   92          3        pos_w  12   
89   93          3        pos_w   7   

                                  processed_assertion     H_P_mw H_N_mw  
0   Frauen haben einen signifikant geringeren Durc...      [5,6]    [1]  
1   Frauen sind psychisch nicht für komplexe Arbei...        [4]    [1]  
2   Frauen haben im statistischen Mittel ein klein...      [7,8]    [1]  
3   Frauenförderung hat fast nur Nachteile für die...        [5]    [1]  
4      Frauen sind im Durchschnitt dümmer als Männer.        [5]  [1,7]  
..                                                ...        ...    ...  
85  Gleichstellung der Geschlechter ist ein Traum ...  [6,7,8,9]   [99]  
86  Frauen in führenden Positionen haben häufig st...        [7]   [99]  
87                   Frauen gehören in die Regierung.        [5]   [99]  
88           Frauen sollten ihren Traumberuf ausüben.        [4]   [99]  
89  Alles was eine Frau tun muss, ist ihre Wünsche...        [9]   [99]  

[90 rows x 7 columns]

In [7]:
### initial six categories can be categorized into two as hate versus nohate
orig_df.loc[orig_df['Cond_remark']=='hate_w_high', 'label']= 1 # hate
orig_df.loc[orig_df['Cond_remark']=='no_hate_w', 'label']= 0 # nohate
orig_df.loc[orig_df['Cond_remark']=='hate_w_med', 'label']= 1 # hate
orig_df.loc[orig_df['Cond_remark']=='hate_m', 'label']= 1 # hate
orig_df.loc[orig_df['Cond_remark']=='neutral_w', 'label']= 0 # nohate
orig_df.loc[orig_df['Cond_remark']=='pos_w', 'label']= 0 # nohate

In [8]:
def predict(model, encodings):
    
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    masks = torch.tensor([[int(e > 0) for e in encodings]], device=device)
    input = torch.tensor([encodings], dtype=torch.long, device=device)
    # get model output
    output = model(input, masks)
    pred_id = torch.argmax(output[0], dim=1).item()
    #pred_label = model.config.id2label[pred_id]

    return pred_id

In [9]:

def main(orig_df, bert_type):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    
    if bert_type=='base':
        tokenizer = AutoTokenizer.from_pretrained("dbmdz/bert-base-german-uncased")   
        model = AutoModelForSequenceClassification.from_pretrained('dbmdz/bert-base-german-uncased', output_hidden_states=True, return_dict=True, output_attentions=True).to(device)

    if bert_type=="germeval18" :   
        tokenizer = AutoTokenizer.from_pretrained("deepset/bert-base-german-cased-hatespeech-GermEval18Coarse")
        model = AutoModelForSequenceClassification.from_pretrained("deepset/bert-base-german-cased-hatespeech-GermEval18Coarse",output_hidden_states=True, return_dict=True, output_attentions=True).to(device)   
    

    # get input

    texts = orig_df['processed_assertion']
    
    # encode input
    encodings = [tokenizer.encode(t) for t in texts]
    
    # predict testset
    predictions = [predict(model, e) for e in tqdm(encodings)]
    
    #print(predictions)
    # save preds
    orig_df[bert_type+'_PREDS'] = predictions
    orig_df.to_csv('gaze4hate_sentence_bert_predictions_'+ bert_type+'.csv', index=False)
    
    labels = orig_df['label']
    #print(labels)

     # evaluate predictions
    print(classification_report(labels, predictions))

In [10]:
main(orig_df, 'base')

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at dbmdz/bert-base-german-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
  0%|          | 0/90 [00:00<?, ?it/s]

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  102,  1648,   423,   366, 18014, 28385, 22226, 24187,  5926,  8791,
         30938,   552,   103]])


  3%|▎         | 3/90 [00:00<00:19,  4.43it/s]

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  102,  1648,   321,  3825,   187,   237,  9586, 18334,  1029,  5056,
           552,   103]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  102,  1648,   423,   197, 12597,  1085,   139,  8689, 30941,  1954,
          2789,   552,   103]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  102,  1648,  6344,   292,  1932,   435, 21736,  9586,   125,  2247,
           552,   103]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  102,  1648,   321,   197,  5541, 12787,   105,   250,   946,   105,
           552,   103]])


  8%|▊         | 7/90 [00:01<00:08,  9.73it/s]

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  102,  1648,   321,   946,   278, 30543,   142,  3033,  5064, 28645,
           552,   103]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  102,  1648,   321,  7034, 19314,   142,  2595,  2247,   552,   103]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  102,  1648,   367,   316,  1454,   143,   321,   167, 12787,   552,
           103]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  102,  1648, 28961,   536,  2140,   179,  1020,   153,  5456,   552,
           103]])


 13%|█▎        | 12/90 [00:01<00:05, 15.18it/s]

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[ 102,  125, 1603, 1744, 5892,  223, 5561,  207, 4165,  323,  187,  552,
          103]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  102,  1648,  2152,   167,  3637,  2647,   143,   235,   271,   173,
          2644, 18660,   334, 30938,   552,   103]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  102, 21629,  1165,   321, 24026,  4968, 19634,   329,   946,   105,
         19289, 30941,   552,   103]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[ 102, 1648, 4826,  281, 6403,  806,  946,  105, 4826,  281, 2823,  552,
          103]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  102,   238, 11702,  7485, 12452,   142,   127,  2679,   207,   167,
         28081,   552,   103]])


 18%|█▊        | 16/90 [00:01<00:04, 15.68it/s]

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[ 102, 1648,  321, 9586, 9342, 7708,  237, 6940,  552,  103]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  102, 22747,   127, 17114,   207,   238, 24026,   291, 28809,   140,
           185,  1648,   552,   103]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  102,  1648,   142, 16093,   166, 10792,   423,   792,  4027, 30948,
         21617, 30937,   980,  5677,   552,   103]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  102,  1648, 20197,   106,   142,   125,  3234,   383,   552,   103]])


 22%|██▏       | 20/90 [00:01<00:04, 16.74it/s]

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  102,  1648,  2152,   597, 11702, 17114,  7244,   216, 10360, 30938,
           552,   103]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  102,  1177,   359,   238,   884,  1575,  1055,   806,   207,  1053,
           946,   167, 25005,   552,   103]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  102,  1648,  1260,  3342,  6446,  1091, 15739,   552,   103]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  102,   946,   105,   143,  1648,   321,   829,  8403, 30942,   552,
           103]])


 27%|██▋       | 24/90 [00:01<00:03, 17.34it/s]

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[ 102, 1648,  367,  316, 1083, 1129,  453, 6252,  181,  267,  552,  103]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  102,  1648,   321,   237, 10483,   143,  2152,   235,   224,   277,
           237,  4035,  1470,   552,   103]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[ 102, 1648, 1794,  173, 6307, 1260, 4585,  375,  281,  946,  105,  552,
          103]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  102,  2391, 17114,  2152,   829, 10128,   318,   552,   103]])


 31%|███       | 28/90 [00:02<00:03, 17.62it/s]

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  102,   829, 22610,   207,   238, 25159,   440,  2004,   552,   103]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  102,  2206,  1055,   106,   197,  3508,  4031,   281,  2254,  6015,
          9586,   597,  1129, 24026,   726,   552,   103]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  102,   125, 17114,   321,   237,   788,   829,   806,   995,   237,
          7034,  1582,   690,   552,   103]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  102, 30596, 30112,  2254,   321, 16063,  1245,   552,   103]])


 36%|███▌      | 32/90 [00:02<00:03, 17.65it/s]

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  102,   233,   773,  1648, 11435, 30937,   143,   233,   773,   946,
         18365,  5986,   552,   103]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  102,   946,   105,  4035,  1470,   235,   185,  1648,   142,  5407,
           310, 18398, 12568,   552,   103]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  102,  1648,  7305,  1055, 24026,   353,   267,   552,   103]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[ 102,  946,  105,  143, 1648,  321,  142,  343, 8714, 1905,  266,  453,
         6252,  181,  276,  552,  103]])


 41%|████      | 37/90 [00:02<00:02, 18.86it/s]

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  102,  1648,   321,   244,  7685,  4625,  5881, 16789,   410,   552,
           103]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  102,  1648,   423,  1630,  7233,   244,  3596, 25248, 24026,   179,
         26810,   127,  2197,  1129,   552,   103]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  102,  1648,   321,   197,  5541, 21055, 30940,   250,   946,   105,
           142, 28544, 21092,   552,   103]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  102,   125, 30425,   223, 13590,   223, 23808,   207,   859,  1453,
           210,  3836,  2005,   552,   103]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  102,  1648,   367,   316,   235,  1761,   271,  1129,   143,  1905,
         18660,   334, 30938,   806,   233,  1234,   142,   948,  1896,   552,
           103]])


 47%|████▋     | 42/90 [00:02<00:02, 19.17it/s]

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  102,  8674,  1648, 15346,   321, 30878, 16076, 30948,   143,  9367,
         13432,   407,   552,   103]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[ 102,  946,  105,  321,  704, 8861,  552,  103]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  102,   946,   105,   321, 12787,   105,   250,  1648,   552,   103]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[ 102,  946,  105,  321,  126,  373, 2136,  454,  690,  250, 1648,  552,
          103]])


 51%|█████     | 46/90 [00:03<00:02, 18.69it/s]

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[ 102,  676,  946,  105,  321, 3289,  296,  552,  103]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[ 102,  946,  105,  321,  237,  125, 6239,  276,  552,  103]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  102,   127,   946,  5970, 12979,   115,   173,  1898,   552,   103]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  102,   946,   105, 20197,   106,   193,   179,   844,   552,   103]])


 56%|█████▌    | 50/90 [00:03<00:02, 18.32it/s]

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  102,   946,   105,   321,   244,  2080, 22426, 30938, 16789,   410,
           552,   103]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[ 102,  946,  105,  663,  670, 2253,  530,  183, 1053, 4268,  552,  103]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  102,   676,   946,   105,   321,  6115,  1667, 30937,  1129,   552,
           103]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  102, 25389,   158,  2480,   423,   366, 18014, 28385, 22226, 24187,
          5926,  8791, 30938,   552,   103]])


 60%|██████    | 54/90 [00:03<00:02, 17.30it/s]

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  102,  1129,   321,  3825,   187,   237,  9586, 18334,  1029,  5056,
           552,   103]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  102,  1129,   423,   197, 12597,  1085,   139,  8689, 30941,  1954,
          2789,   552,   103]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  102, 21769,  2005,   292,  1932,   435, 21736,  9586,   125,  2247,
           552,   103]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  102, 13765,   321,   197,  5541, 12787,   105,   250,  1361,   302,
         19225,   552,   103]])


 64%|██████▍   | 58/90 [00:03<00:02, 15.85it/s]

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  102,  8567,   321,  1012, 30543,   142,  3033,  5064, 28645,   552,
           103]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  102,  7028,  1154, 23823,  7602,   321,  7034, 19314,   142,  3572,
         16772,  3006,   552,   103]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  102,  9628,  2480,   367,   316,  1454,   143,   321,   167, 12787,
           552,   103]])


 67%|██████▋   | 60/90 [00:04<00:01, 15.64it/s]

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  102,  3399, 28961,   410,  2140,   179,  1020,   153,  5456,   552,
           103]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  102,   125,  1603,   859, 12667,   223,  5561,   207,  4165,   323,
           187,   552,   103]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  102, 20032,  2855,  2152,   167,  3637,  2647,   143,   235,   271,
           173,  2644, 18660,   334, 30938,   552,   103]])


 69%|██████▉   | 62/90 [00:04<00:01, 15.05it/s]

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  102,  9146,   321, 24026,  4968, 19634,   329, 16907,   154,   552,
           103]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  102,  7119,  4826,   281,  6403,   806, 24154,   105,  4826,   281,
          2823,   552,   103]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  102,   139, 20886, 30941, 24792,  2297,   142,   127,  2679,   207,
           167, 28081,   552,   103]])


 73%|███████▎  | 66/90 [00:04<00:01, 12.18it/s]

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  102,  2330, 24993,   106,   321,  9586,  4459, 19916,   237,  6940,
           552,   103]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  102, 22747,   127, 17114,  2519,  7424,   792,  4027,   286,  1317,
           552,   103]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  102,  1012,   142, 16093,   166, 10792,   423,   792,  4027, 30948,
         21617, 30937,  4739,  2675, 30937,   552,   103]])


 78%|███████▊  | 70/90 [00:04<00:01, 13.69it/s]

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  102, 24109, 30937, 20197,   106,   142,   125,  3234,   383,   552,
           103]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  102,  3579, 10612,  2152,   597, 11702,   453, 25960,  7244,   216,
         10360, 30938,   552,   103]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  102,  1177,   359,   139,  1501,  1575,  1055,   806,   207,   610,
          6090,   167, 25005,   552,   103]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  102,  1648,   423,   366, 18014, 28385,  3325, 30937,  9747,  2989,
           584,   356,   552,   103]])


 82%|████████▏ | 74/90 [00:05<00:01, 14.87it/s]

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  102,  1648,   321,  3825,   187,  9586, 18334,  1029,  5056,   552,
           103]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  102,  1648,   423,   197, 12597,  1085,   142,   366,  3888,   106,
          3098, 18575,   552,   103]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[ 102, 1648, 6344,  292, 1932,  435, 7233, 9586,  125, 2247,  552,  103]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  102,  1648,   321,   197,  5541, 14091,   250,   946,   105,   552,
           103]])


 87%|████████▋ | 78/90 [00:05<00:00, 15.84it/s]

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  102,  1648,   321,   946,   278,   197, 28581, 12196,  1280, 24026,
          1175,   552,   103]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  102,  1648,   321, 22916,   106,   142,  2595,  2247,   552,   103]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  102,  1648,   367,   316,  1177,   143,   321,   789, 12325,   552,
           103]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[ 102, 1648, 3839, 2140,  179, 1020,  153, 5456,  552,  103]])


 91%|█████████ | 82/90 [00:05<00:00, 16.95it/s]

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[ 102,  125, 1603, 1744, 5892,  223, 5561,  207, 1337, 4344,  209,  552,
          103]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  102,  1648,  2152,   237,   167,  3637,  2647,   143,   235,   271,
           597,  4478, 18660,   334, 30938,   552,   103]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  102, 21629,  1165,   321, 24026,  4968, 19634,   329, 13018,  5926,
          3745, 30937,   552,   103]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  102, 21078,   124,  4826,   281,  6403,   806,  1648,  4826,   281,
          2823,   552,   103]])


 96%|█████████▌| 86/90 [00:05<00:00, 17.64it/s]

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  102,   238,  6727,  7485, 12452,   142,   127,  2679,   207,   167,
         28081,   552,   103]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  102,  1648,   321,  9586,   676, 19916,   832,  6940,   552,   103]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  102, 22747,   127, 17114,   207,   139,  6263,   127,  2247,   552,
           103]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  102,  1648,   142, 16093,   166, 10792,   423,   792,  4027, 30948,
          6246,   980,  5677,   552,   103]])


100%|██████████| 90/90 [00:05<00:00, 15.15it/s]

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  102,  1648, 20197,   106,   142,   125,  2119,   552,   103]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  102,  1648,  2152,  1053,  6263, 11435,   216, 10360, 30938,   552,
           103]])
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])
tensor([[  102,  1177,   359,   238,   884,  1575,  1055,   806,   207,   597,
          5557, 30937,   167, 25005,   552,   103]])
              precision    recall  f1-score   support

         0.0       0.56      0.90      0.69        50
         1.0       0.50      0.12      0.20        40

    accuracy                           0.56        90
   macro avg       0.53      0.51      0.45        90
weighted avg       0.53      0.56      0.47        90



In [16]:
main(orig_df, 'germeval18')

100%|██████████| 90/90 [00:05<00:00, 15.73it/s]


              precision    recall  f1-score   support

         0.0       0.61      0.78      0.68        50
         1.0       0.58      0.38      0.45        40

    accuracy                           0.60        90
   macro avg       0.59      0.58      0.57        90
weighted avg       0.59      0.60      0.58        90



In [17]:
## EXERCISE: 
## you can try this on Davidson data
davidson_sentence_file =  "../day1_annotation_interrateragreement/labeled_data.csv"
davidson_df = pd.read_csv(davidson_sentence_file) 
davidson_df

## Note that it has multiclass label:
## class = class label for majority of CF users. 0 - hate speech 1 - offensive language 2 - neither


Unnamed: 0  count  hate_speech  offensive_language  neither  class  \
0               0      3            0                   0        3      2   
1               1      3            0                   3        0      1   
2               2      3            0                   3        0      1   
3               3      3            0                   2        1      1   
4               4      6            0                   6        0      1   
...           ...    ...          ...                 ...      ...    ...   
24778       25291      3            0                   2        1      1   
24779       25292      3            0                   1        2      2   
24780       25294      3            0                   3        0      1   
24781       25295      6            0                   6        0      1   
24782       25296      3            0                   0        3      2   

                                                   tweet  
0      !!! RT @mayasolovely: As a woman you shouldn't...  
1      !!!!! RT @mleew17: boy dats cold...tyga dwn ba...  
2      !!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...  
3      !!!!!!!!! RT @C_G_Anderson: @viva_based she lo...  
4      !!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...  
...                                                  ...  
24778  you's a muthaf***in lie &#8220;@LifeAsKing: @2...  
24779  you've gone and broke the wrong heart baby, an...  
24780  young buck wanna eat!!.. dat nigguh like I ain...  
24781              youu got wild bitches tellin you lies  
24782  ~~Ruffled | Ntac Eileen Dahlia - Beautiful col...  

[24783 rows x 7 columns]